apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

# This helm chart enables automatic reloading of deployments when ConfigMaps or Secrets change
# https://artifacthub.io/packages/helm/stakater/reloader
helmCharts:
  - name: reloader
    repo: https://stakater.github.io/stakater-charts
    version: 1.1.1
    releaseName: reloader
    namespace: reloader
    valuesFile: values.yaml
