### ByteStash Helm Chart for Kubernetes
### Maintainer: Tin Trung Ngo - trungtinth1011@gmail.com

## Strings for naming overrides
##
nameOverride: ""
fullnameOverride: ""

### ByteStash configs
### ref: https://github.com/jordan-dalby/ByteStash/wiki
###
replicaCount: 3

### Enabling this will persist the `/data` directory with a Persistent Volume
persistence:
  enabled: true
  storageClassName: ""
  size: 4Gi

### Basic configs
bytestash:
  baseUrl: "/"
  debug: false
  disableAccount: false
  disableAllAccount: false
  allowNewAccount: false
  jwtSecret: ""
  jwtExpirity: ""

  ### Existing Kubernetes Secret that contains JWT secret and JWT expiration time
  ### This will override the `bytestash.jwtSecret` and `bytestash.jwtExpirity`
  existingJwtSecret:
    secretName: ""
    jwtKey: ""
    expirityKey: ""

### Ref: https://github.com/jordan-dalby/ByteStash/wiki/Single-Sign%E2%80%90on-Setup
oidc:
  enabled: false
  name: "Single Sign-on"
  issuerUrl: "" # Authentik, Authelia, or Keycloak
  clientId: ""
  clientSecret: ""
  scopes: ""

image:
  repository: ghcr.io/jordan-dalby/bytestash
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.5.6

## Array with extra environment variables to add to the pod. For example:
## extraEnv:
##   - name: ENV01
##     value: "value01"
##
extraEnv: []

## Map with extra environment variables fetched from existing secrets. For example:
## extraEnvSecrets:
##   ENV02:
##     name: extra-secret
##     key: username
extraEnvSecrets: {}

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  httpGet:
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 3
  successThreshold: 1
