apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headscale
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: VPN management
    gethomepage.dev/group: Networking
    gethomepage.dev/icon: tailscale
    gethomepage.dev/name: Headscale
    # Dont generate pihole record for this ingress
    external-dns.alpha.kubernetes.io/ingress-hostname-source: "annotation-only"
spec:
  rules:
    - host: vpn.$(DNS) # DNS will be replaced by kustomize
      http:
        paths:
          - path: /web
            pathType: Prefix
            backend:
              service:
                name: headscale-ui
                port:
                  name: http
