---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: tailscale-authkey
spec:
  encryptedData:
    authkey: AgAbEmIAhL+Cn296KL78LCPR5bYsdXfS/KzOTE00cM2Hm+kmMXtptwHOBdOclPg5Sp/u0kMfHD6C4B5otJoU7iL1Oou5afUFkQT5eTYcTcqNLppvC051LLBI210cQSWihjKQOmSiySf3/5oeygPiTZoV7FTKzXAhyw1jR6Bn4rQgkK9RNzbImR7iFmbO7qdtVTgtG5TCXCpf2tU9qr3OIJWKtFGP925RYk4dTOoed68y5Q5eVrxAySlj/dA4QyW6l0hW2Lxt7iHs+pMwds0RcHC1jbUNgut6rKpZE0ZNuZKD+4oHKm7P2BSra7DzpgrSYwdTAtTUDHoV37ADsPn3Hs2l1X5Y/qHruhkhUi3WILA/yu07JSFrpG9pfv+of29BEAGofRP/lDd5ABpBXbo+OKo/iyp1sU64B8VugQljicdBDdnNhv4fcAJOx5kcLHClSCbgmA+u9rNOR1Q/7L7AmkL51WoOYksdOLc9d62dgHP9vAqYkpxqdF53ni7TxwXHa7Q/VheTcQnbqKd84kQo32KBbjzLEwE/o3HDIukMwW736ZztDirZWQhXnotEthTuNkvRpNqGlHXPRGTQMEsNQKBuUozOI7CvAhUIpHocqYy0zkT2KbEnPEy5oJ5uno5ltq5veGTTN+KLmJD/H4yS/LkRMZIH9tPb6c1CspPQY0byAQxyLNHuhMTUUEYCKO/ZBLCxYdKcJFMTa/BRI4zOsJOHyGNE84Gc2FOCdx88EnQbxwkIOR9ft2zVSnqUzFg/+us=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: tailscale-authkey
    type: Opaque
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Generated using Makefile from
# https://github.com/tailscale/tailscale/tree/main/docs/k8s
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    # Create can not be restricted to a resource name.
    verbs: ["create"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    resourceNames: ["tailscale"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""] # "" indicates the core API group
    resourceNames: ["tailscale-authkey"]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["events"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
subjects:
  - kind: ServiceAccount
    name: "tailscale"
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tailscale
  labels:
    app: tailscale
spec:
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      serviceAccountName: tailscale
      containers:
        - name: tailscale
          image: tailscale/tailscale:v1.78.3
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: TS_STATE_DIR
              value: "/var/lib/tailscale"
            - name: TS_EXTRA_ARGS
              value: >-
                --login-server=http://vpn.dsilva.dev 
                --advertise-exit-node
                --advertise-routes=192.168.1.0/24 
                --accept-dns=true
                --hostname=homelab
            - name: TS_NO_LOGS_NO_SUPPORT
              value: "true"
            # Use node name as hostname
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-authkey
                  key: authkey
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          volumeMounts:
            - name: data-volume
              mountPath: "/var/lib/tailscale"
            - name: dev-net-tun
              mountPath: "/dev/net/tun"
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: tailscale-data
        - name: dev-net-tun
          hostPath:
            path: "/dev/net/tun"
      restartPolicy: Always
