---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: tailscale-authkey
spec:
  encryptedData:
    authkey: AgCOrOef1hF0ZjtBEEdIfH2pVjpM7FaGRTdf+XWv0KlqpwyZLlMAYTFAKQDAcr9kFVYMEqmDF/hQzdckoJdi/wpD8FKheIKcxtD5zLTmKuCVtD4SayTec7TLgmfZFMU3cD5FgeUHCJ0RXeGhh6EIGgxChsFjDfkWwQRPMWDJR6fKuKkLTT9W56/msebUlhAm+w37rNKCR0eNviQ9mHRlsEVjiK/av3BiqHC0bw73s5A9TCUQfHkOn5bupZWngM795yqBxMtsFnBhHsi6WHZVGfKDPjWzzUmfUrOFVL20FXbdFwGqhKdWkaZzZHpobfs3/YlC0U0b1IAxUW0m9bAY/k9z4UKBPAgC8SuHn+I8PI4pDHR03w4gJ/uCMcj+UChf73eM5jOCspxCFaojrktNyGYtMQOHC5eRo9p1k1N64srGAga5292VnPDDohHTU7yTnTL3/bsRiR9D9wQf461xy7v4fpL+lWYS5zJCicZ6sBNZDoe588Est+ofvk+gL58OD4B+WdJG3MMCXa3GlmsBgHJAYLJ1HJqFW4c3WtQkZPo1n7mgx4hYV65m8ahjPXAkxd+jiu9jXT8KZ45eEvstn+aqmsAYm1MDjboe3C6lEJ6qdG0VdaYhoBuJIYt9gVlyIRaymvQKsKZP+NcD85AVsdtpROy7yOFM6W8qK4+jaECeys9J4MtkNYKiZZauXNTtXjKJArBPWlbwSB7v5fiaj3GfbFTJldwtbv0Br8TrIExjghiNY5neOYZ2XKP6+5Yt/Ng=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: tailscale-authkey
      type: Opaque
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Generated using Makefile from
# https://github.com/tailscale/tailscale/tree/main/docs/k8s
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    # Create can not be restricted to a resource name.
    verbs: ["create"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    resourceNames: ["tailscale"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""] # "" indicates the core API group
    resourceNames: ["tailscale-authkey"]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["events"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
subjects:
  - kind: ServiceAccount
    name: "tailscale"
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tailscale
  labels:
    app: tailscale
spec:
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: tailscale
      containers:
        - name: tailscale
          image: tailscale/tailscale:v1.78.3
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: TS_STATE_DIR
              value: "/var/lib/tailscale"
            - name: TS_EXTRA_ARGS
              value: >-
                --login-server=https://vpn.dsilva.dev 
                --advertise-exit-node
                --advertise-routes=192.168.1.0/24,192.168.0.0/24,10.40.0.0/14
                --accept-dns=true
                --hostname=homelab
            - name: TS_NO_LOGS_NO_SUPPORT
              value: "true"
            # Use node name as hostname
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-authkey
                  key: authkey
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          volumeMounts:
            - name: data-volume
              mountPath: "/var/lib/tailscale"
            - name: dev-net-tun
              mountPath: "/dev/net/tun"
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: tailscale-data
        - name: dev-net-tun
          hostPath:
            path: "/dev/net/tun"
      restartPolicy: Always
