# This resource is a TunnelBinding that will allow
# exposing the vpn service to the internet so we can
# connect to it from anywhere
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: vpn-tunnel-binding
subjects:
  - kind: Service	
    name: headscale	
    spec:	
      noTlsVerify: false
tunnelRef:
  kind: ClusterTunnel
  name: homelab-cluster-tunnel