---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: wireguard-peer-conf
spec:
  encryptedData:
    wg0.conf: AgAMBqzfDn4sgNX/MW4qSNs8qFCoz56PFr2Mv5kijJV4nYSH9eXz0Fa2XVgwl9A8nr95WbC3TH9oCrwZETbJhu/upWQOQnIpesB56AsuEodUpvd7GKc/4FQOPs1JyQHWe1C9AnJwUr2CGg+I9kFfGE3QNwI4GH2+jgMIac4F8uJeqT+WDJ516r6RunltugqBOcpMchVe+vS7YklnW41XYRtvheiTS/GRS3xaqu84ZXARuIaLxy9sXmOLzbXfeWAnaL/D+aaohU7+S4ng2EAie4Ly4DFRxRHNBfj+6kEeecmIxx479rjz7bBZrvPkgEJSdPKPxefDIRkxVJC+oFdkcQY2j6JxmK3Q+z2a+5UVIMt0N3MvQMtqwPwMLXsvoKGkWaIW5v1pjcl0KLpl+6T2t0WJC/5W+1E2Vfg31NW/2CLO2tg+8vsR+1DO7E+A9dyPxe+Ln2W3DGqa4/WltiGTq4xDByFKl7KWbfPuqk3dPSzqbg4odvlH8M1gzUHg5de12kz6m+cw70+AM8DIQsHaqxWa6MPk8qIcCYa3dQ/1oRufF2Dr06qaihWvH8r6UEkuARWLdDGMGToj0YPebB+zhi3dRz13QGzTfOmCx5j0OYBbCdROCi5HxGBs2HERM9/bRBUwV67KPwCh4T8EPwRNAqzycm3KCPHXrU6NG9YhOPirgAvP25DvO56Ni1jPlo07H5BQizyQxyltvgBjY22s2vRIcFGZEPj3sbliDagzIW8+ph270ulFj/qBdhRK/B+82Lj5wVTCoAq9lcVJI6s2wl5bcxP7xSKQ45bmOzV9mdMeC4nDsKZ4jM6Z4IPKHgfbqU0fBGjbmkZNwSDE/CdlszVOXlOMuiPQj+yDvp6flVSpX+RRnbo37YfA5Ufp5PKdDAx9JjoOKH3cD+dlA3+Z58N8mIIgRcuQndQl0ajKePfPH38H2rNTgPFD6GqaM4O0LzCVUfMVYigBRNm8KZQ0ATUc0vnTX6fkp+WyMrLao0VNL9Gb2uPjZkBqzYo9R1xSAslTZKjqzJDGCzAql9znrgSPUSR2n0qhd35OOt+iRajcw+H21lU3+L4iakDg
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: wireguard-peer-conf
    type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-peer
  labels:
    app: wireguard-peer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard-peer
  template:
    metadata:
      labels:
        app: wireguard-peer
    spec:
      containers:
        - name: wireguard-peer
          image: ghcr.io/digitallyrefined/docker-wireguard-tunnel:v3
          env:
            # Use the FQDN of the headscale service here
            - name: SERVICES
              value: "peer1:headscale.headscale.svc.cluster.local:8080:8080"
          volumeMounts:
            - name: wireguard-config
              mountPath: /etc/wireguard/wg0.conf
              subPath: wg0.conf
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      volumes:
        - name: wireguard-config
          secret:
            secretName: wireguard-peer-conf
            items:
              - key: wg0.conf
                path: wg0.conf
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard-peer-service
spec:
  selector:
    app: wireguard-peer
  ports:
    - name: wireguard-port
      port: 51820
      targetPort: 51820
      protocol: UDP
  type: ClusterIP
