apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

resources:
  - manifests/alloy-configmap.yaml
  - manifests/ingress.yaml

helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    namespace: grafana-alloy
    releaseName: grafana-alloy
    version: 0.10.1
    valuesFile: values.yaml

replacements:
  - source:
      kind: Ingress
      name: grafana-alloy
      fieldPath: metadata.annotations.dns
    targets:
      - select:
          kind: Ingress
          name: grafana-alloy
        fieldPaths:
          - spec.rules.0.host
        options:
          # This keeps the "alloy." prefix
          delimiter: "."
          index: 1
