apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    namespace: certmanager
    releaseName: certmanager
    version: 1.16.2
    valuesInline:
      installCRDs: true
      podDnsConfig:
        nameservers:
          - "1.1.1.1"
          - "8.8.8.8"

# Load the manifests from the manifests directory
resources:
  - manifests/cloudflare_token.yaml
  - manifests/cluster_issuer.yaml
  - manifests/wildcard_cert.yaml
  - manifests/traefik_tls_store.yaml
