# Custom values for the pihole chart
# https://artifacthub.io/packages/helm/mojo2600/pihole

replicaCount: 1

dnsmasq:
  customSettings:
    # Configure pihole for DHCP server on all network devices except MEO TvBox,
    # otherwise no television :(
    # https://gist.github.com/andrepcg/5999203519c722004c463eb1494559f8
    - dhcp-host=38:e1:f4:4c:e8:ec,set:meo
    - dhcp-option=tag:meo,option:dns-server,192.168.1.254

admin:
  # Use secret specified in "pihole/manifests/admin-password.yaml"
  enabled: true
  existingSecret: "pihole-admin-password"
  passwordKey: "password"


# Following settings are required for running pihole as DHCP server
# https://docs.pi-hole.net/docker/dhcp/
# https://github.com/MoJo2600/pihole-kubernetes/issues/185

hostNetwork: "true" # The pod uses the host network rather than k8s network (to perform a network broadcast on port 67 / DHCP) See  https://docs.pi-hole.net/docker/DHCP/#docker-pi-hole-with-host-networking-mode
privileged: "true" # Give root permission to the pod on the host
webHttp: "55080" # Random HTTP port to prevent clash (because the pod will be on the host network)
webHttps: "55443" # Random HTTPS port to prevent clash (because the pod will be on the host network)
capabilities:
  add:
  - NET_ADMIN

extraEnvVars:
  DNSMASQ_LISTENING: "all" # Listen on all interfaces
  # https://github.com/MoJo2600/pihole-kubernetes/issues/163#issuecomment-872216807
  DHCP_ACTIVE: "true"
  DHCP_START: "192.168.1.64"
  DHCP_END: "192.168.1.253"
  DHCP_ROUTER: "192.168.1.254"
  DHCP_IPv6: "true"
  DHCP_rapid_commit: "true"
  ServerIP: "192.168.1.86"
  TZ: "Europe/Lisbon"


# enables cloudflare tunnel sidecar container
# and sets upstream dns in pihole to leverage it
doh:
  enabled: true
  pullPolicy: Always
  envVars: {
    DOH_UPSTREAM: "https://1.1.1.1/dns-query"
  }
persistentVolumeClaim:
  enabled: true

podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - 127.0.0.1
  - 1.1.1.1
