# fly.toml app configuration file generated for dsilva-vpn-gateway on 2024-12-17T16:16:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# You can redeploy with `fly deploy` after modifying this file
app = 'dsilva-vpn-gateway'
primary_region = 'arn'

[build]
  image = 'ghcr.io/digitallyrefined/docker-wireguard-tunnel:v3'

[env]
  DOMAIN = 'dsilva-vpn-gateway.fly.dev'
  PEERS = "1"
  SERVICES = "peer1:headscale.headscale.svc.cluster.local:8080:8080"

[[mounts]]
  source = "wireguard_data"
  destination = "/etc/wireguard"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
