# fly.toml app configuration file generated for dsilva-vpn-gateway on 2024-12-17T16:16:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# You can redeploy with `fly deploy` after modifying this file
app = 'dsilva-vpn-gateway'
primary_region = 'arn'

[build]
  image = 'ghcr.io/digitallyrefined/docker-wireguard-tunnel:v3'

[env]
  DOMAIN = 'dsilva-vpn-gateway.fly.dev'
  PEERS = "1"
  SERVICES = "peer1:headscale.headscale.svc.cluster.local:8080:80,peer1:headscale.headscale.svc.cluster.local:8443:443"

[[mounts]]
  source = "wireguard_data"
  destination = "/etc/wireguard"

[[services]]
  protocol = "udp"
  internal_port = 51820

  [[services.ports]]
    port = 51820

[[services]]
  protocol = "tcp"
  internal_port = 80

  [[services.ports]]
    port = 80

[[services]]
  protocol = "tcp"
  internal_port = 443

  [[services.ports]]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
