apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

resources:
  - manifests/ingress.yaml

helmCharts:
  - name: headscale
    repo: https://charts.gabe565.com
    namespace: headscale
    releaseName: headscale
    version: 0.14.0
    valuesFile: values.yaml

replacements:
  - source:
      kind: Ingress
      name: headscale
      fieldPath: metadata.annotations.dns
    targets:
      - select:
          kind: Ingress
          name: headscale
        fieldPaths:
          - spec.rules.0.host
        options:
          # This keeps the "vpn." prefix
          delimiter: "."
          index: 1
