apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts


helmCharts:
  - name: headscale
    repo: https://charts.gabe565.com
    namespace: headscale
    releaseName: headscale
    version: 0.14.0
    valuesFile: values.yaml
