# https://artifacthub.io/packages/helm/gabe565/headscale

serviceMonitor:
  main:
    enabled: true

env:
  HEADSCALE_DISABLE_CHECK_UPDATES: "true"
  HEADSCALE_LOG_LEVEL: "warn"
  HEADSCALE_DNS_BASE_DOMAIN: "vpn.lab"
  # Set clients to use Pi-hole as DNS server (192.168.1.86)
  HEADSCALE_DNS_NAMESERVERS_GLOBAL: "192.168.1.86 1.1.1.1"
  HEADSCALE_SERVER_URL: "https://vpn.dsilva.dev"
  HEADSCALE_LISTEN_ADDR: "0.0.0.0:8080"
  # HEADSCALE_TLS_LETSENCRYPT_HOSTNAME: "vpn.dsilva.dev"

persistence:
  config:
    enabled: true
    mountPath: /etc/headscale

sidecars:
  ui:
    image: ghcr.io/gurucomputing/headscale-ui:2024.10.10
    ports:
      - name: http
        containerPort: 81
    # Set environment variables for the sidecar
    env:
      - name: HTTP_PORT
        value: "81"
