apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  labels:
    app: alloy-config
data:
  config.alloy: |
    livedebugging {
      enabled = true
    }

    logging {
      level  = "info"
      format = "logfmt"
    }

    discovery.kubernetes "pods" {
      role = "pod"
    }

    discovery.kubernetes "nodes" {
      role = "node"
    }

    discovery.kubernetes "services" {
      role = "service"
    }

    discovery.kubernetes "endpoints" {
      role = "endpoints"
    }

    discovery.kubernetes "endpointslices" {
      role = "endpointslice"
    }

    discovery.kubernetes "ingresses" {
      role = "ingress"
    }

    otelcol.receiver.otlp "otel_receiver" {
      grpc {
        endpoint = "0.0.0.0:4317"
      }

      http {
        endpoint = "0.0.0.0:4318"
      }

      output {
        metrics = [otelcol.processor.batch.otel_batch_processor.input]
        logs    = [otelcol.processor.batch.otel_batch_processor.input]
        traces  = [otelcol.processor.batch.otel_batch_processor.input]
      }
    }

    otelcol.processor.batch "otel_batch_processor" {
      output {
        metrics = [otelcol.exporter.prometheus.grafana_lab_metrics.input]
        logs    = [otelcol.exporter.loki.grafana_lab_logs.input]
        traces  = [otelcol.exporter.otlp.grafana_lab_traces.input]
      }
    }

    otelcol.exporter.otlp "grafana_lab_traces" {
      client {
        endpoint = "http://monitoring-tempo-distributor.monitoring.svc.cluster.local"
      }
    }

    otelcol.exporter.prometheus "grafana_lab_metrics" {
      forward_to = [prometheus.remote_write.grafana_lab_metrics.receiver]
    }

    prometheus.remote_write "grafana_lab_metrics" {
      endpoint {
          url = "http://monitoring-mimir-nginx.monitoring.svc.cluster.local/api/v1/push"
      }
    }

    otelcol.exporter.loki "grafana_lab_logs" {
      forward_to = [loki.write.grafana_lab_logs.receiver]
    }

    loki.write "grafana_lab_logs" {
      endpoint {
        url = "http://monitoring-loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push"
      }
    }
