---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-alloy
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Grafana Alloy (OpenTelemetry Collector) for logs, metrics, and traces
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: https://avatars.githubusercontent.com/u/49998002?s=200&v=4
    gethomepage.dev/name: Grafana Alloy
spec:
  rules:
    - host: alloy.$(DNS) # DNS will be replaced by kustomize
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-alloy
                port:
                  number: 12345
