---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: academic-editorial-backend-env
  namespace: the-academic-editorial
spec:
  encryptedData:
    DATABASE_URL: AgAz0DMVx7x3gfYnFx0etCIajVkmM+vFTlf+tAXWvaYzbYuP3C+21XkP0vfdk/g0Ub056SxTzhKbTur7DUfcOcX534f0RRWBBRfhlRcGVR4Q+fkwsUyGpSt/R9pNuDcnDzrjz3hCZUt1YHgkFC4ptpExPGbSR88Gl73LnQAm4cUD/LRBZFR4XE5n/CbXGQ0mMaTI1Pk6OCayfn71j1B1mFbkefBlz1K5JKMnYDP2pKt9XZ+FVjDG5vA9lcf4ITIPX2EkvrL7NmXCTFfMu7G2Yt8ZQvchW6iZbg5LkyhcOgX/KpV9s22SDwRZYPlsCmXMMT4S8Amw46TFF81uj0qDh2UUgPDKraHHd9Rr7A/C1k6zcDrqe2QYTuly/hynAq3aGrrOD4bvoCIyvSXj5C0FP3BNt4kx7NfhXyZm9GUSwAmxensRw8OXlO/XAp1VD4QglnJbGjalvoTEyk9aFvtoy80qLe6SJ0VCCYnuLO5S6GhIaSl+FebYNOyE+fG062+gYUR7fEe3qMd0qLD685V2f+cFW8eXDyvCskJXY8nOw3/1jh3n+h/TkivP6y8EDjeq+aJ0fdgz0mRcJffmBwRdANW6OCBIvNFf0Gu95IYp8ryhYkGKtbLssBOrbHX+ZRytUkmQaukKChOr2WzU5ECzDFIZOydq0NY/AhqHw1lpcmdTtL27gaxxFnKcY3Nrc5gNIVmFWgBpTE9NsRN2NbC2aVhLyibB5HBAWSNwLjE43gerWLMyrXRdjPHKQfNua9mLplbWmXy79OF+0bRQwW21khWiZq+WF7OjcWH/GKP7SUZWZ9SEi+G+Po5aC4No2rOzO9vY120LQV32fmIjErmpQgQCFNIfZ3HgXeF71GGb4PTp7O4=
    DJANGO_SECRET_KEY: AgCdNsdkVcxQbWJ1il5wzuwgli1gSE9gQAStEuQGNq1rrXuKFVleYjCvwNpbUzSfbkLv4xww8m1f2HgV8q6cWLpPUz89PyP0n6NLUedn4TH5IvlgJvCQOTM1xi8DaBFGV0zC5OL4AU47lUqr3ETQ6xKr1fl6lJdzn27wWf9tSOTdxniI9LwKAgxhiqFXO5uIZ8yPWwE6d8OB0DvhaQeekbWKkKjGR+upzBXcJ4qontYQFUTYHVd8mxpvKZiLAtfyBgF4ZPwzU8ft7rnEirni7E6gzi06458+xtRc9njzPIDQKaFQV1LCix91Ne2W4tgGM9NytxMBaEvkUyNpuChoMfn7ykSMUmE5D4TKGpVzRQNfhyAbaJsaNhHTZt4hKdFgeihjsyk2O7TXmbo0T4m+ztFvu3ApLFYN/Ny8ma73jQPr/aAin5/BlMFUj3sCuaF7bkqPVGE1yXkypj7Jzy2zTxNwJp/d7aGem/EWllRUr6ux1ttzE9BIcs+x9M9FG10fviLqU6GC91j0e+EFLPbA4TgpinQtqAyDMiswVfgNwqTVLckQEfZeaJg48Kk5di2ineyM/9ktXy4IF5h7edpr+KBYu0zHXWeZOuljUo11Dwg0YsehivzYP+aee+e/ee/r++923hlkaEJRpLn0JnvdRyMrFb5Iv1cQ4FQ1v1F8tUb0B4YUw8+2G87YBKQVzLWA0cLtMHAZPhIMNoO1LcmRUCxUUibWf4K7cIuts20IXUOdw9afxv+nY/pkoIRobnEDJ8r3KkibxBC8bOoMSkDsZ6ipsJnJ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: academic-editorial-backend-env
      namespace: the-academic-editorial
    type: Opaque
