---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gh-copilot-api-token
spec:
  encryptedData:
    GH_TOKEN: AgC24XNQr0dWvaV8RS933bn+a1f835EhWgzvUgvNvqIg5YGqupGUkwgzScCDlyp677vQYU/ZK4naPksFHS3m2A5XZqPcya6Lbl4Pce0kh1qQytHF6UmULBDGgsMOujymSGOvUHryUrEU03DmXNX7YkmGflmWlkwjQ8k/K6BjgHhgIqlOs5AgnZGTmuAjhTgHO7C7/VDpdFjtFexa6j0X1+2yTA0eRjOxTwjyTIasg1oTy1jYuqS2+rlQZUc0z+yQ142GJ/SRGoniSTLEps22GX7UJKvJfNdO4SKzxIoxbHTZGS1tbaEU7IAAsH9qNVLswehty28HucUrP/RiKAbxQF9hlPSMpZOnXsl1O/sIFO631UhgCHizS+vBuAhCneNNrxzgPkEJuU7LaYueiw+GVQzBTjl1J5MRdkArY7vnOxUCfyMLBmpWR6hvM0wzGBvdxHV1axEouDu4ur38Ov/SeWRW/W4F6sat55xDS0zkq2R4wkhNbHojFmSZ/SXY0JzlgJcm7ReEZnARy+jDqZn61+pMvL+hGqlmT6Piah4Net4aIsKUswSyZxGn9erfzxkZxTlJe3EQxRkIiSxQAQzv4mxRj1P5mrCvsZ6rpfj+d9yk9XpVlp6poSDOEmg+jgTDCxOfCgL4M2oWXMkj5MOctTEmAg5JY2KT9N3Lhcgvqs8YNyJsqPj3SQNSpxGa7tQ0Ul7jWO7FOdc0y72VQ+MhQ9Gk0ItEjScC0QJawfy+Pu4PDSc9SSZV+V/V
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: gh-copilot-api-token
    type: Opaque
