---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gitsync-token
spec:
  encryptedData:
    GH_TOKEN: AgCLuHUgGP4ZlCe6Z4Ir+UOZnnl3lB1GZz5SbufqoDjmKjLiRhPJJoe7lcbCwoLR/L13iktNP0yuxTW/d/4voxwXh0c2Ev4DQL+J4NMBoQDT59Rk07ujagbad4P1HRLqOl3CcI5bq6qUzRLCEt4Gv8go2ZZtJm+Avjss91sbjevq3LuHeoYgrwuBLi6aH4oDukq+UNY4wTFzq3fATCgefhKO4BCpFkuJiSeDzJuhHcEnoRAEKGP7fO5vsM94GGDEWFjmTrRqdNNFCJ1/oDs4HZLO3f8qP5iMriAxGFavv/TwYjO4xqDCy9WiqMPLOrecrvDbGM617ZouFXFvs/pf2prsZ+rFT2MGWoyHamArF4eVhvfqs8dt9ELDJNghNvj5v78nDMAlCAvpGkb2TdV11BzA/CrI9ck4kB1VPK6YBrKXV49ezCbuuZX0sXGHM9dBHlKYIIqge1bX8zpslN6Rb12UTXLJLegyMzgEbJeYqAGuz3NbEP7ivUuam+UAX/cljr+kAqbAfWKcBDl/vLyyn0TvlY/+RHoA43Xiu52P09gXzi9N4brdiZlbclF1oSfnGIK4lbFQDSu3S00XvlCP8HgUp8fjuYMp9IVeoushDWK2kkegdft8lMuly08E1/EPR9lpeJY8JsSIIvfLKx9d5B5PC+JHkiNnsgpYLTFb/hdbhZtBEssNEs77fnA+egJexOPdM3uP4Y+n7Umh/GVbIr1ncH390sfOU7V91Ph7ATw+SXxy+qFMO/vt
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: gitsync-token
    type: Opaque
