apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: the-academic-editorial-tunnel-binding
subjects:
  - kind: Service
    name: academic-editorial
tunnelRef:
  kind: ClusterTunnel
  name: homelab-cluster-tunnel
