services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace/
      # Map the docker socket so we can run docker commands inside the dev container
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ../.env
    dns:
      - 192.168.1.86 # Our pihole server, otherwise terraform will not reach Zitadel IDP
    # network_mode: host
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/bash -c "while sleep 1000; do :; done"
    user: root


  