---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    creationTimestamp: null
    name: grafana-oidc-credentials
spec:
    encryptedData:
        GF_AUTH_GENERIC_CLIENT_ID: AgAxHJ3j4masC0Bjak+ft23MBNpLg7s2iK21qXvyxLeG7efxvw86LKuLTr/ne/rA0cFOoeUjGMibjV8Mg645VvlbuojvVlcWmb9y0RUsqCkJ6da6wSxJu3e5PQF3XckiFMAsyCw0GUd4fRg/9WKjQthRNf4CW2QuxcogrxYbcD64dsWaodHI0UdeaEP2gnorszUQdU8NwE9zVnPb6DxKxgLpOsvb/YFhQcuvjxBYYdRBAv+j5uqsFT9C8epNbyyUh3vuYSAV8V2hi27xpcRwl3+7pXdeNpBKZlIqlCqVDLNlD8/klf/L3SewlbtkVQOWYL4Do+xvT3mwiKuTTY4sydB+ji4KgVjBWMFFXagNjwpjsb2CLSi73fY+1AV9lUy6whZhcamy/HMoCWaZ/4y2HLxGnelgJT1Pyq8/OmGAOaOvyqY2eT51e4RfgMDUMgqCKqXFe5lD+3sZwOV/OGsN/aVhERtEFdOn3jcPckXIFSgpdYOdHL3aLWbITodfajY+4ttynYo+8PdHmU1yOy8ATN7sC23uI34pd7k/ySb4S0Xxx9Oa3CCEF4mOXbPODabafPvq7adtog8jBm0SJOc9AIqpLtnxov4Lbu8FVtG8p0xDVGXUOFnPb8pNUr9Xnrtv5lvsLaY4buBGeeZBbj6a7eUBHpETcqVKxJBmPfgb2iWkxfXA/bQpamuD6yuHCxH6Fr5/cnan9qi77oQfJpBqMYtyNhQ=
        GF_AUTH_GENERIC_CLIENT_SECRET: AgAS66CNWb5tvBiDFqNY7zS5S44fCKnD8jIV1oUxhWkVxcw5dCbnKJA+nrHTc8MfiF90+sUsKPEsiQYg6tn7ms5K2Ypqrn+pRrSVyaq6m2byUvccGF12i1akBjxMVl3RkHUW0mJoViZBKtCcKUEaeKAKKYZjUiWkOx/a4UXzOk9/UJRf08x0Ku6YMwHEHpQ7yHOFq8Tdi5Em44e8vWVwGppNOW4x975hS6C7642vonI4nSVoUMZvC58GG82GZBynDXNHgln+Pq+tA5U8K3CsnvpE9ETd3QQ0ucscNtSIqLGCvazpOD5aO6a4i55gRyKErHHvgXe37PP8etybuPyD89h8qohOQPyZYwcFLlBZhry54zC2FEb1ixOoRjPN8XU/UNleajrXWYRJTOxqsxd72G+gfxEj6C+xm5wEDln3DCC5gdDrFVIOksk9R8LVIo2EA4RtKn7XI/WYbwKw4s9PKvh1zFcloKWFId5fgxdstyW4H0/kF89/bEgBqUF9iyTCHy1yCS/uRUxy53/aiN7AmkwjqZN75B2fBIUX4iSnpV67L6FCGspVaQaogleVvosmi0mQ9PwnF/F6fCJK7LEDqI5QikQpO+VScM9Bettrd5EW5+YGpxsUZzlf7j4nAD4eNqL9XbjCtQiOBxNfREucSq8owGel46ry8WxczVu4pm+Je4oxuq1TRJn72B2PoDtGwPjtlGn4BAIMWXu1cs7lGLG6UnvY6MG+/ot7nOA6S+XONJPZSgECD0CZxuXMr1JXTd37AaEFzxDo2CpUYaL1nMiS
    template:
        metadata:
            annotations:
                sealedsecrets.bitnami.com/cluster-wide: "true"
            creationTimestamp: null
            name: grafana-oidc-credentials
        type: Opaque
