---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    GIT_TOKEN: AgAGmBEpZBb3bCXhLUE7AKU36MUP4ZTT3IhVuREHXtEcgGHgcSFbkdC0Henas7/eFGscyjS/J6U0hJRuJ/6D7uTu3J/QQwKbkQ1ZC6/GmiSP+RjkT1vXPEuU7MU5W8L80OBNi5rqK10bJ7eHt4+ATc6huDabjeJU02KeFqB2vTZYNL45jr0uA6aryyHYnOtsrWjoruEuKQYQnt/QF0UJOlcm7MUYGpEwckJh4/QpZyBeWii/eX/+noqbWhXVgcLTGwhp+cg26l3BBTTRZwjBl0nJtvvF0+dE/59vyKv0D7rB60sbR4nUU9aiPqX7u38wX48vKbb7S3aqPK9sSim9sWirV0xAGL4qJTWVCjZ3lr1VSYM1LwORKYjPzFUDbmGr6kTkQ2p8agQNGDxG2M2dHsREfzCRpZcWOKbPw7tRWkMIjX49qeeTAOI04Z1Wwr+wRDJnPdR/lPCLzwOD96uqdEyloXTdXiX0eGrrgj7tmqOIn3PcgCgMSwdrPiX4ZZydmwKKByOTFhWriwRn+YMZ++GxrY+lkEZMCdkH7xR09I7yMtVE+4gfbEVabBFtJN3kwWIG5oHhOC63MiOkzHqaqSk7138499/sdKaZFrMEwhAubiVpybCXsvPhXBSh0qcgMYxLH3oGQo2dOyw0sSzcZSwE2Z73kJjHdYOKRn5UIoJ6Csgu1NpkPV3HcOyh+n4fAL7hbmUog64FaXk8rBu0Hggjq4HU65gyiQmDdDdoZMaDpggG7pO/bOk7
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: git-credentials
    type: Opaque
