apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Home automation
    gethomepage.dev/group: Home
    gethomepage.dev/icon: home-assistant
    gethomepage.dev/name: Home Assistant
spec:
  rules:
    # DNS will be replaced by kustomize
    - host: home.$(DNS)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homeassistant
                port:
                  name: http