# Point to home assistant running outside the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-external
spec:
  type: ExternalName
  externalName: 192.168.1.86
  ports:
    - port: 8123
      targetPort: 8123
      protocol: TCP
      name: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Home automation
    gethomepage.dev/group: Home
    gethomepage.dev/icon: home-assistant
    gethomepage.dev/name: Home Assistant
spec:
  rules:
    # DNS will be replaced by kustomize
    - host: home.$(DNS)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homeassistant-external
                port:
                  name: http
