apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

resources:
  - manifests/ingress.yaml

helmCharts:
  - name: sftpgo
    repo: oci://ghcr.io/sftpgo/helm-charts
    namespace: sftpgo
    releaseName: sftpgo
    version: 0.37.0
    valuesFile: values.yaml

replacements:
  - source:
      kind: Ingress
      name: sftpgo-web
      fieldPath: metadata.annotations.dns
    targets:
      - select:
          kind: Ingress
          name: sftpgo-web
        fieldPaths:
          - spec.rules.0.host
        options:
          # This keeps the "sftpgo." prefix
          delimiter: "."
          index: 1
