grafana:
  enabled: true
  replicas: 1
  plugins:
    # Install the "grafana-piechart-panel" plugin
    # https://grafana.com/grafana/plugins/grafana-piechart-panel
    - grafana-piechart-panel

  # Inject the variables from the secret into the Grafana configuration
  # This secret was created with "ClusterSecret" in Terraform
  envFromSecret: grafana-oidc-credentials

  # https://artifacthub.io/packages/helm/grafana/grafana#how-to-securely-reference-secrets-in-grafana-ini
  extraSecretMounts:
    - name: grafana-oidc-credentials
      secretName: grafana-oidc-credentials
      defaultMode: 0440
      mountPath: /etc/secrets/grafana-oidc-credentials
      readOnly: true

  grafana.ini:
    # Need to configure the following for the Oauth2 redirect URI to be correctly
    # set
    server:
      domain: "grafana.lab.local"
      root_url: "http://grafana.lab.local/"
    log:
      level: debug
      filters: "oauth.generic_oauth:debug"
    # Configure OIDC. The client id and secret should be read automatically
    # from the "grafana-oidc-credentials" secret
    auth.basic:
      enabled: false
    auth.generic_oauth:
      auto_login: true
      enabled: true
      name: IDP
      allow_sign_up: true
      # Read the client id and secret from the mounted secret
      client_id: $__file{/etc/secrets/grafana-oidc-credentials/GF_AUTH_GENERIC_CLIENT_ID}
      client_secret: $__file{/etc/secrets/grafana-oidc-credentials/GF_AUTH_GENERIC_CLIENT_SECRET}
      scopes: openid email profile
      auth_url: http://idp.lab.local/oauth/v2/authorize
      token_url: http://idp.lab.local/oauth/v2/token
      api_url: http://idp.lab.local/oidc/v1/userinfo
      email_attribute_path: email
      login_attribute_path: email
      name_attribute_path: name
      # Role mapping from Zitadel IDP to Grafana roles
      # 299425082244071627 is the project ID of Grafana in Zitadel
      role_attribute_path: >
        (contains(keys(@."urn:zitadel:iam:org:project:299425082244071627:roles"), 'grafana-viewer') && 'Viewer')
        ||
        (contains(keys(@."urn:zitadel:iam:org:project:299425082244071627:roles"), 'grafana-editor') && 'Editor')
        ||
        (contains(keys(@."urn:zitadel:iam:org:project:299425082244071627:roles"), 'grafana-admin') && 'Admin')

loki:
  enabled: true

mimir:
  enabled: true
  # https://github.com/grafana/mimir/discussions/5158#discussioncomment-6413922
  structuredConfig:
    memberlist:
      cluster_label: "mimir"
      cluster_label_verification_disabled: true

tempo:
  enabled: true
  ingester:
    config:
      replication_factor: 1
  traces:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true
  distributor:
    topologySpreadConstraints: null
    affinity: null
    config:
      # -- Enable to log every received span to help debug ingestion or calculate span error distributions using the logs
      log_received_spans:
        enabled: true
