apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

resources:
  - manifests/ingress.yaml
  - manifests/admin-credentials.yaml
  - manifests/node-svc.yaml

helmCharts:
  - name: influxdb2
    repo: https://helm.influxdata.com/
    namespace: influxdb
    releaseName: influxdb
    version: 2.1.2
    valuesFile: values.yaml
    includeCRDs: true

replacements:
  - source:
      kind: Ingress
      name: influxdb
      fieldPath: metadata.annotations.dns
    targets:
      - select:
          kind: Ingress
          name: influxdb
        fieldPaths:
          - spec.rules.0.host
        options:
          # This keeps the "influxdb." prefix
          delimiter: "."
          index: 1
