apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

resources:
  - manifests/ingress.yaml

helmCharts:
  - name: homeassistant
    repo: https://charts.cryptic.systems/volker.raschek
    namespace: home-assistant
    releaseName: homeassistant
    version: 0.1.7
    valuesFile: values.yaml

replacements:
  - source:
      kind: Ingress
      name: homeassistant
      fieldPath: metadata.annotations.dns
    targets:
      - select:
          kind: Ingress
          name: homeassistant
        fieldPaths:
          - spec.rules.0.host
        options:
          # This keeps the "home." prefix
          delimiter: "."
          index: 1
