apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/ingress.yaml

replacements:
  - source:
      kind: Ingress
      name: homeassistant
      fieldPath: metadata.annotations.dns
    targets:
      - select:
          kind: Ingress
          name: homeassistant
        fieldPaths:
          - spec.rules.0.host
        options:
          # This keeps the "home." prefix
          delimiter: "."
          index: 1
