image:
  repository: ghcr.io/diogosilva30/the-academic-editorial/frontend
  tag: "1.37.0"
  pullPolicy: Always

replicaCount: 1

service:
  name: academic-editorial
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false

env:
  - name: VITE_GOOGLE_CLIENT_ID
    value: "134486215324-h9rkud4n4id0b9m2411a2dh77rnnnaa9.apps.googleusercontent.com"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi
