image:
  repository: ghcr.io/diogosilva30/the-academic-editorial/frontend
  tag: "0.3.0"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi
