apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts/the-academic-editorial

resources:
  - manifests/ingress.yaml
  - manifests/backend-env.yaml
  - manifests/ghcr-auth.yaml
  - manifests/gitsync-token.yaml
  - manifests/gh-copilot-api-token.yaml
  - manifests/default-serviceaccount.yaml
  - manifests/tunnel-binding.yaml

helmCharts:
  - name: backend
    namespace: the-academic-editorial
    releaseName: backend
    valuesFile: backend-values.yaml

  - name: frontend
    namespace: the-academic-editorial
    releaseName: frontend
    valuesFile: frontend-values.yaml

replacements:
  - source:
      kind: Ingress
      name: the-academic-editorial
      fieldPath: metadata.annotations.external_dns
    targets:
      - select:
          kind: Ingress
          name: the-academic-editorial
        fieldPaths:
          - spec.rules.0.host
        options:
          delimiter: "."
          index: 1
